# Generated by Django 4.2.17 on 2024-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
